// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLN05O-irAdzTiaCiWIUx7JgFQ6V9Z7hQ',
    appId: '1:432171226999:web:e912963aae2c3c9c58f372',
    messagingSenderId: '432171226999',
    projectId: 'fir-2-auth-f83bc',
    authDomain: 'fir-2-auth-f83bc.firebaseapp.com',
    storageBucket: 'fir-2-auth-f83bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_HfvoSATfPTACMJEXe2pLhAeMCc9tKI',
    appId: '1:432171226999:android:6cb6a21c4f3edc2958f372',
    messagingSenderId: '432171226999',
    projectId: 'fir-2-auth-f83bc',
    storageBucket: 'fir-2-auth-f83bc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLN05O-irAdzTiaCiWIUx7JgFQ6V9Z7hQ',
    appId: '1:432171226999:web:06190255b6d5a22458f372',
    messagingSenderId: '432171226999',
    projectId: 'fir-2-auth-f83bc',
    authDomain: 'fir-2-auth-f83bc.firebaseapp.com',
    storageBucket: 'fir-2-auth-f83bc.firebasestorage.app',
  );
}
